/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:77704442-2274-4321-bb04-f64d776ab479",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_gl75zuVtc",
    "aws_user_pools_web_client_id": "3bhv5ffke7ss8of73qtmnokk8v",
    "oauth": {}
};


export default awsmobile;
