// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:bf447d86-e3cb-4e05-8553-cbdc385972f1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PMp6sasz8",
    "aws_user_pools_web_client_id": "7o227b795s89oskivtap5tuae",
    "oauth": {}
};


export default awsmobile;
